const products = [
  {
    id: 0,
    name: "T200",
    category: "T-shirt",
    price: 19.99,
    image: "../images/product-1.jpg",
    desc: "T-shirt",
    size: "mediam",
    quantity : 1,

  },
  {
    id: 1,
    name: "Sh45",
    category: "shoes",
    price: 19.99,
    image: "../images/product-2.jpg",
    desc: "shoes",
    size: "mediam",
    quantity : 1,

  },
  {
    id: 2,
    name: "P12",
    category: "fasion",
    price: 19.99,
    image: "../images/product-3.jpg",
    desc: "fasion",
    size: "mediam",
    quantity : 1,
    
  },
  {
    id: 3,
    name: " T52",
    category: "T-shirt",
    price: 30.99,
    image: "../images/product-4.jpg",
    desc: "T-shirt",
    size: "mediam",
    quantity : 1,
  },
  {
    id: 4,

    name: " Sh42",
    category: "Shoes",
    price: 19.99,
    image: "../images/product-5.jpg",
    desc: "Shoes",
    size: "mediam",
    quantity : 1,
  },
  {
    id: 5,
    name: "T11",
    category: "T-shirt",
    price: 25.99,
    image: "../images/product-6.jpg",
    desc: "T-shirt",
    size: "mediam",
    quantity : 1,
  },
  {
    id: 6,
    name: "Sock17",
    category: "Socks",
    price: 19.99,
    image: "../images/product-7.jpg",
    desc: "Socks",
    size: "mediam",
    quantity : 1,
  },
  {
    id: 7,
    name: "W457",
    category: "Watch",
    price: 19.99,
    image: "../images/product-8.jpg",
    desc: "Watch",
    size: "mediam",
    quantity : 1,
  },
  {
    id: 8,
    name: "W758",
    category: "Watch",
    price: 19.99,
    image: "../images/product-9.jpg",
    desc: "Watch",
    size: "mediam",
    quantity : 1,
  },
  {
    id: 9,
    name: "Sh75",
    category: "Shoes",
    price: 19.99,
    image: "../images/product-10.jpg",
    desc: "Shoes",
    size: "mediam",
    quantity : 1,
  },
  {
    id: 10,
    name: "Sh89",
    category: "Shoes",
    price: 19.99,
    image: "../images/product-11.jpg",
    desc: "Shoes",
    size: "mediam",
    quantity : 1,
  },
  {
    id: 11,
    name: "P16",
    category: "fasion",
    price: 19.99,
    image: "../images/product-12.jpg",
    desc: "fasion",
    size: "mediam",
    quantity : 1,
  },
];
